# Generated by Django 3.2.20 on 2023-09-02 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('address', models.TextField(max_length=255, verbose_name='Адрес')),
                ('DateOfBirth', models.DateField(verbose_name='Дата рождения')),
                ('telephone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=1, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='diagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название болезни')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название уровня')),
                ('AmountRequiredToTransfer', models.IntegerField(verbose_name='Сумма необходимая для перехода')),
                ('AmountOfDiscount', models.FloatField(verbose_name='Скидка')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Уровни клиента',
                'verbose_name_plural': 'Уровни клиента',
            },
        ),
        migrations.CreateModel(
            name='listOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость услуги')),
            ],
            options={
                'verbose_name': 'Список услуг',
                'verbose_name_plural': 'Список услуг',
            },
        ),
        migrations.CreateModel(
            name='listOfVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfVisit', models.DateTimeField(db_index=True, verbose_name='Дата посещения')),
                ('confirmationOfVisit', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Подтверждение записи')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Список посещений',
                'verbose_name_plural': 'Список посещений',
            },
        ),
        migrations.CreateModel(
            name='loadingLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название уровня загрузки')),
            ],
            options={
                'verbose_name': 'Уровни загрузки',
                'verbose_name_plural': 'Уровни загрузки',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.FloatField(verbose_name='Заработная плата')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('norma', models.IntegerField(null=True, verbose_name='Нормальное кол-во пациентов в час')),
                ('isDoctor', models.BooleanField(null=True, verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='visitCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.client')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.position')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО')),
                ('DateOfBirth', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='StaffPhoto/%Y/%m/%d', verbose_name='Фото')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='Паспорт')),
                ('telephone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('address', models.TextField(max_length=255, verbose_name='Адрес')),
                ('EmploymentDate', models.DateField(verbose_name='Дата приема на работу')),
                ('TheLevelOfEducation', models.CharField(max_length=40, verbose_name='Уровень образования')),
                ('EducationalInstitution', models.CharField(max_length=255, verbose_name='Образовательное учреждение')),
                ('YearOfEnding', models.IntegerField()),
                ('DiplomaSpecialty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Специальность по диплому')),
                ('experience', models.IntegerField(null=True, verbose_name='Опыт работы в годах')),
                ('PlaceOfWork', models.CharField(max_length=255, verbose_name='Место работы')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.position')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='services_rendered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=models.Model, to='ClinicWebsite.listofservice', verbose_name='Оказанная услуга')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.listofvisits', verbose_name='Посещение')),
            ],
            options={
                'verbose_name': 'Оказанная услуга',
                'verbose_name_plural': 'Оказанные услуги',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='День недели')),
                ('timeFrom', models.CharField(max_length=10, verbose_name='С')),
                ('timeTo', models.CharField(max_length=10, verbose_name='До')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'График работы',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='NewsPhoto/%Y/%m/%d', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='loadingDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.staff', verbose_name='Сотрудник')),
                ('loading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.loadinglevels', verbose_name='Загрузка')),
            ],
            options={
                'verbose_name': 'Загрузка врачей',
                'verbose_name_plural': 'Загрузка врачей',
            },
        ),
        migrations.AddField(
            model_name='listofvisits',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.staff', verbose_name='Врач'),
        ),
        migrations.CreateModel(
            name='clientCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата размещения проверки')),
                ('time', models.TimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.staff', verbose_name='Сотрудник')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.levels'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.IntegerField(verbose_name='Сумма')),
                ('payment', models.BooleanField(default=False, null=True, verbose_name='Оплата')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.listofvisits', verbose_name='Посещение')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='assigned_diagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий врача')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.diagnoses', verbose_name='Диагноз')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClinicWebsite.listofvisits', verbose_name='Посещение')),
            ],
            options={
                'verbose_name': 'Поставленный диагноз',
                'verbose_name_plural': 'Поставленный диагнозы',
            },
        ),
    ]
